#!/usr/bin/env python
import sys
from wirelessprobe import probe_ap

def fmt_dict(d, keys):
    return ' '.join("%s=%s" % (k,d[k]) for k in keys)

def probe(ip):
    info = probe_ap(ip)
    if info:
        keys = info.keys()
        keys.remove("ip")
        keys.remove("interface")
        print fmt_dict(info, ['ip','interface'] + keys)
        

if __name__ == "__main__":
    ip = sys.argv[1]
    probe(ip)
