#!/usr/bin/env python
import sys
import datetime
from wirelessprobe import probe_ap

def fmt_dict(d, keys):
    return ' '.join("%s=%s" % (k,d[k]) for k in keys)

def probe(ip):
    info = probe_ap(ip)
    if info:
        keys = info.keys()
        keys.remove("ip")
        keys.remove("interface")
        info['ts'] = datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        print fmt_dict(info, ['ts', 'ip','interface'] + keys)
        

if __name__ == "__main__":
    ip = sys.argv[1]
    probe(ip)
