#!/bin/bash
iface=$(cat /etc/wireless_interface.conf)

get_var () {
    k=$1
    cat /etc/wireless_probe.ini | grep $k | cut -d ' ' -f 3
}

restart_wireless () {
    timeout 5 ifdown $iface
    ifconfig $iface 0.0.0.0
    ifconfig $iface down
    pkill wpa_supplicant
    rm /var/lib/dhcp/dhclient.${iface}.leases
    sleep 2
    ifup $iface
}

main () {
    ping_host=$(get_var ping_host)
    if ping -qc 3 $ping_host >/dev/null; then
        #echo "$ping_host rechable!"
        exit 0
    fi

    echo "$ping_host not rechable!"
    echo "Restarting wireless"
    restart_wireless
}

main
