#!/usr/bin/env python
import sys

def red(txt):
    CSI="\x1B["
    RESET=CSI+"m"
    return CSI+"31;40m" + txt + RESET

def color(line):
    if 'ok=False' in line:
        return red(line)
    else:
        return line
    

def main():
    for line in iter(sys.stdin.readline, ''):
        line = color(line)
        sys.stdout.write(line)
        sys.stdout.flush()

if __name__ == "__main__":
    main()
